language: android
android:
  components:
    - platform-tools
    - build-tools-23.0.3
    - android-15
    - extra-android-m2repository
install:
  - true
script:
  - ./gradlew build connectedCheck
  - TERM=dumb ./gradlew assembleDebug